"""Smth

Revision ID: 5acadfe32ea6
Revises: cbfbd3ca9dd3
Create Date: 2024-06-13 00:55:15.593819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5acadfe32ea6'
down_revision: Union[str, None] = 'cbfbd3ca9dd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
