"""Smth

Revision ID: cbfbd3ca9dd3
Revises: b15ed3a2aac8
Create Date: 2024-06-13 00:51:47.203760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbfbd3ca9dd3'
down_revision: Union[str, None] = 'b15ed3a2aac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
